name: CD

on:
  push:
    branches: [main]


#  It should have a single job called Deploy
#  It should checkout the code
#  It should set up the Go toolchain
#  It should build the app using the scripts/buildprod.sh script

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: ./scripts/buildprod.sh