name: CD

on:
  push:
    branches: [main]

#  It should have a single job called Deploy
#  It should checkout the code
#  It should set up the Go toolchain
#  It should build the app using the scripts/buildprod.sh script

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: ./scripts/buildprod.sh
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Build and push Docker image
        run: gcloud builds submit --tag europe-southwest1-docker.pkg.dev/notely-417417/notely-ar-repo/dockerelite/notely:latest .
